# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/19/bin/cmake/bin/cmake

# The command to remove a file.
RM = /snap/clion/19/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sosa/MEGAsync/Tercero/SegundoCuatrimestre/TecModAlg/hiclures-tools

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sosa/MEGAsync/Tercero/SegundoCuatrimestre/TecModAlg/hiclures-tools

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/19/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/19/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sosa/MEGAsync/Tercero/SegundoCuatrimestre/TecModAlg/hiclures-tools/CMakeFiles /home/sosa/MEGAsync/Tercero/SegundoCuatrimestre/TecModAlg/hiclures-tools/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sosa/MEGAsync/Tercero/SegundoCuatrimestre/TecModAlg/hiclures-tools/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rw

# Build rule for target.
rw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rw
.PHONY : rw

# fast build rule for target.
rw/fast:
	$(MAKE) -f CMakeFiles/rw.dir/build.make CMakeFiles/rw.dir/build
.PHONY : rw/fast

#=============================================================================
# Target rules for targets named hiclures

# Build rule for target.
hiclures: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hiclures
.PHONY : hiclures

# fast build rule for target.
hiclures/fast:
	$(MAKE) -f CMakeFiles/hiclures.dir/build.make CMakeFiles/hiclures.dir/build
.PHONY : hiclures/fast

src/filehandle.o: src/filehandle.c.o

.PHONY : src/filehandle.o

# target to build an object file
src/filehandle.c.o:
	$(MAKE) -f CMakeFiles/rw.dir/build.make CMakeFiles/rw.dir/src/filehandle.c.o
	$(MAKE) -f CMakeFiles/hiclures.dir/build.make CMakeFiles/hiclures.dir/src/filehandle.c.o
.PHONY : src/filehandle.c.o

src/filehandle.i: src/filehandle.c.i

.PHONY : src/filehandle.i

# target to preprocess a source file
src/filehandle.c.i:
	$(MAKE) -f CMakeFiles/rw.dir/build.make CMakeFiles/rw.dir/src/filehandle.c.i
	$(MAKE) -f CMakeFiles/hiclures.dir/build.make CMakeFiles/hiclures.dir/src/filehandle.c.i
.PHONY : src/filehandle.c.i

src/filehandle.s: src/filehandle.c.s

.PHONY : src/filehandle.s

# target to generate assembly for a file
src/filehandle.c.s:
	$(MAKE) -f CMakeFiles/rw.dir/build.make CMakeFiles/rw.dir/src/filehandle.c.s
	$(MAKE) -f CMakeFiles/hiclures.dir/build.make CMakeFiles/hiclures.dir/src/filehandle.c.s
.PHONY : src/filehandle.c.s

src/kmer_counter.o: src/kmer_counter.c.o

.PHONY : src/kmer_counter.o

# target to build an object file
src/kmer_counter.c.o:
	$(MAKE) -f CMakeFiles/rw.dir/build.make CMakeFiles/rw.dir/src/kmer_counter.c.o
	$(MAKE) -f CMakeFiles/hiclures.dir/build.make CMakeFiles/hiclures.dir/src/kmer_counter.c.o
.PHONY : src/kmer_counter.c.o

src/kmer_counter.i: src/kmer_counter.c.i

.PHONY : src/kmer_counter.i

# target to preprocess a source file
src/kmer_counter.c.i:
	$(MAKE) -f CMakeFiles/rw.dir/build.make CMakeFiles/rw.dir/src/kmer_counter.c.i
	$(MAKE) -f CMakeFiles/hiclures.dir/build.make CMakeFiles/hiclures.dir/src/kmer_counter.c.i
.PHONY : src/kmer_counter.c.i

src/kmer_counter.s: src/kmer_counter.c.s

.PHONY : src/kmer_counter.s

# target to generate assembly for a file
src/kmer_counter.c.s:
	$(MAKE) -f CMakeFiles/rw.dir/build.make CMakeFiles/rw.dir/src/kmer_counter.c.s
	$(MAKE) -f CMakeFiles/hiclures.dir/build.make CMakeFiles/hiclures.dir/src/kmer_counter.c.s
.PHONY : src/kmer_counter.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/hiclures.dir/build.make CMakeFiles/hiclures.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/hiclures.dir/build.make CMakeFiles/hiclures.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/hiclures.dir/build.make CMakeFiles/hiclures.dir/src/main.c.s
.PHONY : src/main.c.s

src/read_write_occurrences.o: src/read_write_occurrences.c.o

.PHONY : src/read_write_occurrences.o

# target to build an object file
src/read_write_occurrences.c.o:
	$(MAKE) -f CMakeFiles/rw.dir/build.make CMakeFiles/rw.dir/src/read_write_occurrences.c.o
.PHONY : src/read_write_occurrences.c.o

src/read_write_occurrences.i: src/read_write_occurrences.c.i

.PHONY : src/read_write_occurrences.i

# target to preprocess a source file
src/read_write_occurrences.c.i:
	$(MAKE) -f CMakeFiles/rw.dir/build.make CMakeFiles/rw.dir/src/read_write_occurrences.c.i
.PHONY : src/read_write_occurrences.c.i

src/read_write_occurrences.s: src/read_write_occurrences.c.s

.PHONY : src/read_write_occurrences.s

# target to generate assembly for a file
src/read_write_occurrences.c.s:
	$(MAKE) -f CMakeFiles/rw.dir/build.make CMakeFiles/rw.dir/src/read_write_occurrences.c.s
.PHONY : src/read_write_occurrences.c.s

src/seq_distances.o: src/seq_distances.c.o

.PHONY : src/seq_distances.o

# target to build an object file
src/seq_distances.c.o:
	$(MAKE) -f CMakeFiles/hiclures.dir/build.make CMakeFiles/hiclures.dir/src/seq_distances.c.o
.PHONY : src/seq_distances.c.o

src/seq_distances.i: src/seq_distances.c.i

.PHONY : src/seq_distances.i

# target to preprocess a source file
src/seq_distances.c.i:
	$(MAKE) -f CMakeFiles/hiclures.dir/build.make CMakeFiles/hiclures.dir/src/seq_distances.c.i
.PHONY : src/seq_distances.c.i

src/seq_distances.s: src/seq_distances.c.s

.PHONY : src/seq_distances.s

# target to generate assembly for a file
src/seq_distances.c.s:
	$(MAKE) -f CMakeFiles/hiclures.dir/build.make CMakeFiles/hiclures.dir/src/seq_distances.c.s
.PHONY : src/seq_distances.c.s

src/sequence.o: src/sequence.c.o

.PHONY : src/sequence.o

# target to build an object file
src/sequence.c.o:
	$(MAKE) -f CMakeFiles/rw.dir/build.make CMakeFiles/rw.dir/src/sequence.c.o
	$(MAKE) -f CMakeFiles/hiclures.dir/build.make CMakeFiles/hiclures.dir/src/sequence.c.o
.PHONY : src/sequence.c.o

src/sequence.i: src/sequence.c.i

.PHONY : src/sequence.i

# target to preprocess a source file
src/sequence.c.i:
	$(MAKE) -f CMakeFiles/rw.dir/build.make CMakeFiles/rw.dir/src/sequence.c.i
	$(MAKE) -f CMakeFiles/hiclures.dir/build.make CMakeFiles/hiclures.dir/src/sequence.c.i
.PHONY : src/sequence.c.i

src/sequence.s: src/sequence.c.s

.PHONY : src/sequence.s

# target to generate assembly for a file
src/sequence.c.s:
	$(MAKE) -f CMakeFiles/rw.dir/build.make CMakeFiles/rw.dir/src/sequence.c.s
	$(MAKE) -f CMakeFiles/hiclures.dir/build.make CMakeFiles/hiclures.dir/src/sequence.c.s
.PHONY : src/sequence.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... rw"
	@echo "... hiclures"
	@echo "... src/filehandle.o"
	@echo "... src/filehandle.i"
	@echo "... src/filehandle.s"
	@echo "... src/kmer_counter.o"
	@echo "... src/kmer_counter.i"
	@echo "... src/kmer_counter.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/read_write_occurrences.o"
	@echo "... src/read_write_occurrences.i"
	@echo "... src/read_write_occurrences.s"
	@echo "... src/seq_distances.o"
	@echo "... src/seq_distances.i"
	@echo "... src/seq_distances.s"
	@echo "... src/sequence.o"
	@echo "... src/sequence.i"
	@echo "... src/sequence.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

