# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sosa/MEGAsync/Tercero/SegundoCuatrimestre/TecModAlg/hiclures-tools

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sosa/MEGAsync/Tercero/SegundoCuatrimestre/TecModAlg/hiclures-tools

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sosa/MEGAsync/Tercero/SegundoCuatrimestre/TecModAlg/hiclures-tools/CMakeFiles /home/sosa/MEGAsync/Tercero/SegundoCuatrimestre/TecModAlg/hiclures-tools/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sosa/MEGAsync/Tercero/SegundoCuatrimestre/TecModAlg/hiclures-tools/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hiclures

# Build rule for target.
hiclures: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hiclures
.PHONY : hiclures

# fast build rule for target.
hiclures/fast:
	$(MAKE) -f CMakeFiles/hiclures.dir/build.make CMakeFiles/hiclures.dir/build
.PHONY : hiclures/fast

filehandle.o: filehandle.c.o

.PHONY : filehandle.o

# target to build an object file
filehandle.c.o:
	$(MAKE) -f CMakeFiles/hiclures.dir/build.make CMakeFiles/hiclures.dir/filehandle.c.o
.PHONY : filehandle.c.o

filehandle.i: filehandle.c.i

.PHONY : filehandle.i

# target to preprocess a source file
filehandle.c.i:
	$(MAKE) -f CMakeFiles/hiclures.dir/build.make CMakeFiles/hiclures.dir/filehandle.c.i
.PHONY : filehandle.c.i

filehandle.s: filehandle.c.s

.PHONY : filehandle.s

# target to generate assembly for a file
filehandle.c.s:
	$(MAKE) -f CMakeFiles/hiclures.dir/build.make CMakeFiles/hiclures.dir/filehandle.c.s
.PHONY : filehandle.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/hiclures.dir/build.make CMakeFiles/hiclures.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/hiclures.dir/build.make CMakeFiles/hiclures.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/hiclures.dir/build.make CMakeFiles/hiclures.dir/main.c.s
.PHONY : main.c.s

sequence.o: sequence.c.o

.PHONY : sequence.o

# target to build an object file
sequence.c.o:
	$(MAKE) -f CMakeFiles/hiclures.dir/build.make CMakeFiles/hiclures.dir/sequence.c.o
.PHONY : sequence.c.o

sequence.i: sequence.c.i

.PHONY : sequence.i

# target to preprocess a source file
sequence.c.i:
	$(MAKE) -f CMakeFiles/hiclures.dir/build.make CMakeFiles/hiclures.dir/sequence.c.i
.PHONY : sequence.c.i

sequence.s: sequence.c.s

.PHONY : sequence.s

# target to generate assembly for a file
sequence.c.s:
	$(MAKE) -f CMakeFiles/hiclures.dir/build.make CMakeFiles/hiclures.dir/sequence.c.s
.PHONY : sequence.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... hiclures"
	@echo "... edit_cache"
	@echo "... filehandle.o"
	@echo "... filehandle.i"
	@echo "... filehandle.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... sequence.o"
	@echo "... sequence.i"
	@echo "... sequence.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

